import { GenericAdminRecord } from './admin-data.service';

export type FieldType = 'text' | 'date' | 'number' | 'textarea' | 'password' | 'select';

export interface AdminField {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  placeholder?: string;
  col?: string;
  hidden?: boolean;
  options?: AdminFilterOption[];
  optionsEndpoint?: string;
  optionValueKey?: string;
  optionValueKeys?: string[];
  optionLabelKeys?: string[];
  optionValueType?: 'number' | 'string';
  optionParentKey?: string;
  dependsOnField?: string;
  showWhenField?: string;
  showWhenValues?: unknown[];
}

export interface AdminFilterOption {
  label: string;
  value: string;
  parentValue?: unknown;
  inactive?: boolean;
  source?: GenericAdminRecord;
}

export interface AdminFilter {
  key: string;
  label: string;
  type: 'text' | 'select';
  fields: string[];
  placeholder?: string;
  options?: AdminFilterOption[];
  optionsEndpoint?: string;
  optionValueKey?: string;
  optionValueKeys?: string[];
  optionLabelKeys?: string[];
}

export interface AdminEntityConfig {
  key: string;
  title: string;
  subtitle: string;
  icon: string;
  endpoint: string;
  idKey: string;
  statusKey?: string;
  searchFields?: string[];
  searchPlaceholder?: string;
  filters?: AdminFilter[];
  fields: AdminField[];
  columns: AdminField[];
  emptyRecord: GenericAdminRecord;
}

export const ADMIN_ENTITY_ORDER = [
  'estados',
  'estados-vinculacion',
  'facultades',
  'carreras',
  'mallas',
  'ciclos',
  'periodos',
  'tutores',
  'responsables',
  'instituciones',
  'proyectos',
  'documentos',
  'estudiantes',
  'matriculas-proyecto',
  'estudiante-documentos',
  'planificaciones-vinculacion',
  'usuarios',
];

const ACTIVE_STATE_OPTIONS: AdminFilterOption[] = [
  { label: 'Todas', value: '' },
  { label: 'Activas', value: 'ACTIVO' },
  { label: 'Inactivas', value: 'INACTIVO' },
];

const ACTIVE_STATE_FORM_OPTIONS: AdminFilterOption[] = [
  { label: 'Activo', value: 'ACTIVO' },
  { label: 'Inactivo', value: 'INACTIVO' },
];

const ENROLLMENT_STATE_OPTIONS: AdminFilterOption[] = [
  { label: 'Todas', value: '' },
  { label: 'Abiertas', value: 'ACTIVO' },
  { label: 'Cerradas', value: 'INACTIVO' },
];

const ENROLLMENT_STATE_FORM_OPTIONS: AdminFilterOption[] = [
  { label: 'Abierta', value: 'ACTIVO' },
  { label: 'Cerrada', value: 'INACTIVO' },
];

const DOCUMENT_STATE_OPTIONS: AdminFilterOption[] = [
  { label: 'Todos', value: '' },
  { label: 'Pendiente', value: 'PENDIENTE' },
  { label: 'Aprobado', value: 'APROBADO' },
  { label: 'Rechazado', value: 'RECHAZADO' },
];

const ENROLLMENT_PROGRESS_STATE_OPTIONS: AdminFilterOption[] = [
  { label: 'Todos', value: '' },
  { label: 'En proceso', value: 'EN PROCESO' },
  { label: 'Aprobado', value: 'APROBADO' },
  { label: 'Desaprobado', value: 'DESAPROBADO' },
];

const DOCUMENT_ASSIGNMENT_OPTIONS: AdminFilterOption[] = [
  { label: 'No asignar a estudiantes', value: 'NINGUNO' },
  { label: 'Asignar a todos los estudiantes', value: 'TODOS' },
  { label: 'Asignar por carrera', value: 'CARRERA' },
  { label: 'Asignar por ciclo', value: 'CICLO' },
  { label: 'Asignar por carrera y ciclo', value: 'CARRERA_CICLO' },
];

export const ADMIN_ENTITIES: Record<string, AdminEntityConfig> = {
  estados: {
    key: 'estados',
    title: 'Estado documentos',
    subtitle: 'Define los estados usados por documentos y procesos.',
    icon: 'pe-7s-check icon-gradient bg-grow-early',
    endpoint: 'estados',
    idKey: 'idEstado',
    statusKey: 'nomEstado',
    searchFields: ['nomEstado'],
    searchPlaceholder: 'Buscar por nombre',
    fields: [
      { key: 'nomEstado', label: 'Nombre', type: 'text', required: true, placeholder: 'Aprobado', col: 'col-md-5' },
      { key: 'desEstado', label: 'Descripcion', type: 'textarea', placeholder: 'Detalle del estado', col: 'col-md-7' },
    ],
    columns: [
      { key: 'idEstado', label: '#', type: 'number' },
      { key: 'nomEstado', label: 'Nombre', type: 'text' },
      { key: 'desEstado', label: 'Descripcion', type: 'text' },
    ],
    emptyRecord: { nomEstado: '', desEstado: '' },
  },
  'estados-vinculacion': {
    key: 'estados-vinculacion',
    title: 'Estados vinculacion',
    subtitle: 'Estados que describen la situacion de vinculacion del estudiante.',
    icon: 'pe-7s-way icon-gradient bg-night-fade',
    endpoint: 'estados-vinculacion',
    idKey: 'idEstado',
    statusKey: 'nomEstado',
    searchFields: ['nomEstado'],
    searchPlaceholder: 'Buscar por nombre',
    fields: [
      { key: 'nomEstado', label: 'Nombre', type: 'text', required: true, placeholder: 'Activo', col: 'col-md-5' },
      { key: 'desEstado', label: 'Descripcion', type: 'textarea', placeholder: 'Detalle del estado', col: 'col-md-7' },
    ],
    columns: [
      { key: 'idEstado', label: '#', type: 'number' },
      { key: 'nomEstado', label: 'Nombre', type: 'text' },
      { key: 'desEstado', label: 'Descripcion', type: 'text' },
    ],
    emptyRecord: { nomEstado: '', desEstado: '' },
  },
  facultades: {
    key: 'facultades',
    title: 'Facultades',
    subtitle: 'Registra facultades antes de crear carreras.',
    icon: 'pe-7s-culture icon-gradient bg-mean-fruit',
    endpoint: 'facultades',
    idKey: 'idFacultad',
    statusKey: 'estadoFacultad',
    searchFields: ['nomFacultad'],
    searchPlaceholder: 'Buscar por nombre de facultad',
    filters: [
      { key: 'estado', label: 'Estado', type: 'select', fields: ['estadoFacultad'], options: ACTIVE_STATE_OPTIONS },
    ],
    fields: [
      { key: 'nomFacultad', label: 'Nombre', type: 'text', required: true, placeholder: 'Facultad de Ingenieria', col: 'col-md-4' },
      { key: 'direcFacultad', label: 'Direccion', type: 'text', required: true, placeholder: 'Campus principal', col: 'col-md-4' },
      { key: 'estadoFacultad', label: 'Estado', type: 'select', required: true, options: ACTIVE_STATE_FORM_OPTIONS, col: 'col-md-4' },
    ],
    columns: [
      { key: 'idFacultad', label: '#', type: 'number' },
      { key: 'nomFacultad', label: 'Facultad', type: 'text' },
      { key: 'direcFacultad', label: 'Direccion', type: 'text' },
      { key: 'estadoFacultad', label: 'Estado', type: 'text' },
    ],
    emptyRecord: { nomFacultad: '', direcFacultad: '', estadoFacultad: 'ACTIVO' },
  },
  carreras: {
    key: 'carreras',
    title: 'Carreras',
    subtitle: 'Registra carreras asociadas a una facultad.',
    icon: 'pe-7s-study icon-gradient bg-happy-itmeo',
    endpoint: 'carreras',
    idKey: 'idCarrera',
    statusKey: 'estadoCarrera',
    searchFields: ['nomCarrera', 'idFacultad', 'facultad.nomFacultad'],
    searchPlaceholder: 'Buscar por carrera o facultad',
    filters: [
      { key: 'estado', label: 'Estado', type: 'select', fields: ['estadoCarrera'], options: ACTIVE_STATE_OPTIONS },
      {
        key: 'facultad',
        label: 'Facultad',
        type: 'select',
        fields: ['idFacultad'],
        optionsEndpoint: 'facultades',
        optionValueKey: 'idFacultad',
        optionLabelKeys: ['nomFacultad'],
      },
    ],
    fields: [
      { key: 'nomCarrera', label: 'Nombre', type: 'text', required: true, col: 'col-md-4' },
      {
        key: 'idFacultad',
        label: 'Facultad',
        type: 'select',
        required: true,
        optionsEndpoint: 'facultades',
        optionValueKey: 'idFacultad',
        optionLabelKeys: ['nomFacultad', 'direcFacultad'],
        optionValueType: 'number',
        col: 'col-md-4',
      },
      { key: 'estadoCarrera', label: 'Estado', type: 'select', required: true, options: ACTIVE_STATE_FORM_OPTIONS, col: 'col-md-4' },
    ],
    columns: [
      { key: 'idCarrera', label: '#', type: 'number' },
      { key: 'nomCarrera', label: 'Carrera', type: 'text' },
      { key: 'facultad.nomFacultad', label: 'Facultad', type: 'text' },
      { key: 'estadoCarrera', label: 'Estado', type: 'text' },
    ],
    emptyRecord: { nomCarrera: '', estadoCarrera: 'ACTIVO', idFacultad: '' },
  },
  mallas: {
    key: 'mallas',
    title: 'Mallas',
    subtitle: 'Administra las mallas asociadas a cada carrera.',
    icon: 'pe-7s-network icon-gradient bg-happy-fisher',
    endpoint: 'mallas',
    idKey: 'idMalla',
    searchFields: ['nomMalla', 'desMalla', 'carrera.nomCarrera'],
    searchPlaceholder: 'Buscar por malla o carrera',
    filters: [
      {
        key: 'carrera',
        label: 'Carrera',
        type: 'select',
        fields: ['idCarrera'],
        optionsEndpoint: 'carreras',
        optionValueKey: 'idCarrera',
        optionLabelKeys: ['nomCarrera'],
      },
    ],
    fields: [
      { key: 'nomMalla', label: 'Nombre', type: 'text', required: true, col: 'col-md-4' },
      { key: 'desMalla', label: 'Descripcion', type: 'textarea', col: 'col-md-5' },
      {
        key: 'idCarrera',
        label: 'Carrera',
        type: 'select',
        required: true,
        optionsEndpoint: 'carreras',
        optionValueKey: 'idCarrera',
        optionLabelKeys: ['nomCarrera', 'facultad.nomFacultad'],
        optionValueType: 'number',
        col: 'col-md-3',
      },
    ],
    columns: [
      { key: 'idMalla', label: '#', type: 'number' },
      { key: 'nomMalla', label: 'Malla', type: 'text' },
      { key: 'desMalla', label: 'Descripcion', type: 'text' },
      { key: 'carrera.nomCarrera', label: 'Carrera', type: 'text' },
    ],
    emptyRecord: { nomMalla: '', desMalla: '', idCarrera: '' },
  },
  ciclos: {
    key: 'ciclos',
    title: 'Ciclos',
    subtitle: 'Define los ciclos academicos para los estudiantes.',
    icon: 'pe-7s-repeat icon-gradient bg-ripe-malin',
    endpoint: 'ciclos',
    idKey: 'idCiclo',
    statusKey: 'estadoCiclo',
    searchFields: ['nomCiclo'],
    searchPlaceholder: 'Buscar por nombre de ciclo',
    filters: [
      { key: 'estado', label: 'Estado', type: 'select', fields: ['estadoCiclo'], options: ACTIVE_STATE_OPTIONS },
    ],
    fields: [
      { key: 'nomCiclo', label: 'Nombre', type: 'text', required: true, placeholder: 'Octavo', col: 'col-md-6' },
      { key: 'estadoCiclo', label: 'Estado', type: 'select', required: true, options: ACTIVE_STATE_FORM_OPTIONS, col: 'col-md-6' },
    ],
    columns: [
      { key: 'idCiclo', label: '#', type: 'number' },
      { key: 'nomCiclo', label: 'Ciclo', type: 'text' },
      { key: 'estadoCiclo', label: 'Estado', type: 'text' },
    ],
    emptyRecord: { nomCiclo: '', estadoCiclo: 'ACTIVO' },
  },
  periodos: {
    key: 'periodos',
    title: 'Periodos de vinculacion',
    subtitle: 'Gestiona las fechas y el estado de los periodos academicos.',
    icon: 'pe-7s-date icon-gradient bg-mean-fruit',
    endpoint: 'periodos',
    idKey: 'idPeriodo',
    statusKey: 'estadoPeriodo',
    searchFields: ['fechInicio', 'fechFin', 'estadoPeriodo'],
    searchPlaceholder: 'Buscar por mes o anio',
    filters: [
      { key: 'estado', label: 'Estado', type: 'select', fields: ['estadoPeriodo'], options: ACTIVE_STATE_OPTIONS },
    ],
    fields: [
      { key: 'fechInicio', label: 'Fecha de inicio', type: 'date', required: true, col: 'col-md-4' },
      { key: 'fechFin', label: 'Fecha de fin', type: 'date', required: true, col: 'col-md-4' },
      { key: 'estadoPeriodo', label: 'Estado', type: 'select', required: true, options: ACTIVE_STATE_FORM_OPTIONS, col: 'col-md-4' },
    ],
    columns: [
      { key: 'idPeriodo', label: '#', type: 'number' },
      { key: 'fechInicio', label: 'Inicio', type: 'date' },
      { key: 'fechFin', label: 'Fin', type: 'date' },
      { key: 'estadoPeriodo', label: 'Estado', type: 'text' },
    ],
    emptyRecord: { fechInicio: '', fechFin: '', estadoPeriodo: 'ACTIVO' },
  },
  tutores: {
    key: 'tutores',
    title: 'Tutores',
    subtitle: 'Registra tutores antes de crear matriculas de proyecto.',
    icon: 'pe-7s-id icon-gradient bg-premium-dark',
    endpoint: 'tutores',
    idKey: 'idTutor',
    statusKey: 'estadoTutor',
    searchFields: ['cedulaTutor', 'nombreTutor'],
    searchPlaceholder: 'Buscar por cedula o nombre',
    filters: [
      { key: 'estado', label: 'Estado', type: 'select', fields: ['estadoTutor'], options: ACTIVE_STATE_OPTIONS },
    ],
    fields: [
      { key: 'cedulaTutor', label: 'Cedula', type: 'text', required: true, col: 'col-md-4' },
      { key: 'nombreTutor', label: 'Nombre completo', type: 'text', required: true, col: 'col-md-4' },
      { key: 'correoTutor', label: 'Correo', type: 'text', required: true, col: 'col-md-4' },
      { key: 'telefonoTutor', label: 'Telefono', type: 'text', required: true, col: 'col-md-4' },
      { key: 'estadoTutor', label: 'Estado', type: 'select', required: true, options: ACTIVE_STATE_FORM_OPTIONS, col: 'col-md-4' },
    ],
    columns: [
      { key: 'idTutor', label: '#', type: 'number' },
      { key: 'cedulaTutor', label: 'Cedula', type: 'text' },
      { key: 'nombreTutor', label: 'Nombre completo', type: 'text' },
      { key: 'estadoTutor', label: 'Estado', type: 'text' },
    ],
    emptyRecord: { cedulaTutor: '', nombreTutor: '', correoTutor: '', telefonoTutor: '', estadoTutor: 'ACTIVO' },
  },
  responsables: {
    key: 'responsables',
    title: 'Responsables',
    subtitle: 'Administra responsables asignables a la planificacion de vinculacion.',
    icon: 'pe-7s-id icon-gradient bg-grow-early',
    endpoint: 'responsables',
    idKey: 'idResponsable',
    statusKey: 'estadoResponsable',
    searchFields: ['nomResponsable', 'correoResponsable'],
    searchPlaceholder: 'Buscar por nombre o correo',
    filters: [
      { key: 'estado', label: 'Estado', type: 'select', fields: ['estadoResponsable'], options: ACTIVE_STATE_OPTIONS },
    ],
    fields: [
      { key: 'nomResponsable', label: 'Nombre', type: 'text', required: true, col: 'col-md-4' },
      { key: 'correoResponsable', label: 'Correo', type: 'text', col: 'col-md-4' },
      { key: 'estadoResponsable', label: 'Estado', type: 'select', required: true, options: ACTIVE_STATE_FORM_OPTIONS, col: 'col-md-4' },
    ],
    columns: [
      { key: 'idResponsable', label: '#', type: 'number' },
      { key: 'nomResponsable', label: 'Responsable', type: 'text' },
      { key: 'correoResponsable', label: 'Correo', type: 'text' },
      { key: 'estadoResponsable', label: 'Estado', type: 'text' },
    ],
    emptyRecord: { nomResponsable: '', correoResponsable: '', estadoResponsable: 'ACTIVO' },
  },
  instituciones: {
    key: 'instituciones',
    title: 'Instituciones',
    subtitle: 'Registra las instituciones antes de crear proyectos.',
    icon: 'pe-7s-home icon-gradient bg-sunny-morning',
    endpoint: 'instituciones',
    idKey: 'idInstitucion',
    statusKey: 'estadoInstitucion',
    searchFields: ['nomInstitucion'],
    searchPlaceholder: 'Buscar por nombre de institucion',
    filters: [
      { key: 'estado', label: 'Estado', type: 'select', fields: ['estadoInstitucion'], options: ACTIVE_STATE_OPTIONS },
    ],
    fields: [
      { key: 'nomInstitucion', label: 'Nombre', type: 'text', required: true, col: 'col-md-4' },
      { key: 'desInstitucion', label: 'Descripcion', type: 'textarea', col: 'col-md-5' },
      { key: 'estadoInstitucion', label: 'Estado', type: 'select', required: true, options: ACTIVE_STATE_FORM_OPTIONS, col: 'col-md-3' },
    ],
    columns: [
      { key: 'idInstitucion', label: '#', type: 'number' },
      { key: 'nomInstitucion', label: 'Institucion', type: 'text' },
      { key: 'desInstitucion', label: 'Descripcion', type: 'text' },
      { key: 'estadoInstitucion', label: 'Estado', type: 'text' },
    ],
    emptyRecord: { nomInstitucion: '', desInstitucion: '', estadoInstitucion: 'ACTIVO' },
  },
  proyectos: {
    key: 'proyectos',
    title: 'Proyectos',
    subtitle: 'Administra proyectos, fechas, tutor textual e institucion.',
    icon: 'pe-7s-portfolio icon-gradient bg-happy-itmeo',
    endpoint: 'proyectos',
    idKey: 'idProyecto',
    statusKey: 'estadoProyecto',
    searchFields: ['nombreProyecto', 'tutor.nombreTutor', 'tutor.cedulaTutor', 'fechaInicioP', 'fechaFinP', 'institucion.nomInstitucion'],
    searchPlaceholder: 'Buscar por nombre, tutor, institucion o fecha',
    filters: [
      {
        key: 'tutor',
        label: 'Tutor',
        type: 'select',
        fields: ['idTutor', 'tutor.nombreTutor', 'tutor.cedulaTutor'],
        optionsEndpoint: 'tutores',
        optionValueKey: 'idTutor',
        optionLabelKeys: ['nombreTutor'],
      },
      {
        key: 'institucion',
        label: 'Institucion',
        type: 'select',
        fields: ['idInstitucion'],
        optionsEndpoint: 'instituciones',
        optionValueKey: 'idInstitucion',
        optionLabelKeys: ['nomInstitucion'],
      },
      { key: 'estado', label: 'Estado', type: 'select', fields: ['estadoProyecto'], options: ACTIVE_STATE_OPTIONS },
    ],
    fields: [
      { key: 'nombreProyecto', label: 'Nombre', type: 'text', required: true, placeholder: 'Proyecto de vinculacion', col: 'col-md-6' },
      {
        key: 'idTutor',
        label: 'Tutor',
        type: 'select',
        required: true,
        optionsEndpoint: 'tutores',
        optionValueKey: 'idTutor',
        optionLabelKeys: ['nombreTutor', 'cedulaTutor'],
        optionValueType: 'number',
        col: 'col-md-6',
      },
      {
        key: 'idPeriodoProyecto',
        label: 'Periodo de vinculacion',
        type: 'select',
        required: true,
        optionsEndpoint: 'periodos',
        optionValueKey: 'idPeriodo',
        optionLabelKeys: ['fechInicio', 'fechFin'],
        optionValueType: 'number',
        col: 'col-md-4',
      },
      { key: 'fechaInicioP', label: 'Fecha de inicio', type: 'date', required: true, hidden: true },
      { key: 'fechaFinP', label: 'Fecha de fin', type: 'date', required: true, hidden: true },
      { key: 'estadoProyecto', label: 'Estado', type: 'select', required: true, options: ACTIVE_STATE_FORM_OPTIONS, col: 'col-md-4' },
      {
        key: 'idInstitucion',
        label: 'Institucion',
        type: 'select',
        required: true,
        optionsEndpoint: 'instituciones',
        optionValueKey: 'idInstitucion',
        optionLabelKeys: ['nomInstitucion', 'desInstitucion'],
        optionValueType: 'number',
        col: 'col-md-4',
      },
      { key: 'descripcionProyecto', label: 'Descripcion', type: 'textarea', required: true, placeholder: 'Describe el alcance del proyecto', col: 'col-md-12' },
    ],
    columns: [
      { key: 'idProyecto', label: '#', type: 'number' },
      { key: 'nombreProyecto', label: 'Proyecto', type: 'text' },
      { key: 'tutor.nombreTutor', label: 'Tutor', type: 'text' },
      { key: 'institucion.nomInstitucion', label: 'Institucion', type: 'text' },
      { key: 'fechaInicioP', label: 'Inicio', type: 'date' },
      { key: 'fechaFinP', label: 'Fin', type: 'date' },
      { key: 'estadoProyecto', label: 'Estado', type: 'text' },
    ],
    emptyRecord: {
      nombreProyecto: '',
      idPeriodoProyecto: '',
      fechaInicioP: '',
      fechaFinP: '',
      descripcionProyecto: '',
      idInstitucion: '',
      estadoProyecto: 'ACTIVO',
      idTutor: '',
    },
  },
  documentos: {
    key: 'documentos',
    title: 'Documentos',
    subtitle: 'Define documentos y su estado base.',
    icon: 'pe-7s-file icon-gradient bg-arielle-smile',
    endpoint: 'documentos',
    idKey: 'idDocumento',
    statusKey: 'estadoDocumento',
    searchFields: ['nombreDocumento', 'estadoDocumento'],
    searchPlaceholder: 'Buscar por nombre de documento',
    filters: [
      { key: 'estadoDocumento', label: 'Estado', type: 'select', fields: ['estadoDocumento'], options: ACTIVE_STATE_OPTIONS },
    ],
    fields: [
      { key: 'nombreDocumento', label: 'Nombre', type: 'text', required: true, col: 'col-md-5' },
      { key: 'estadoDocumento', label: 'Estado', type: 'select', required: true, options: ACTIVE_STATE_FORM_OPTIONS, col: 'col-md-3' },
      { key: 'linkModeloDocumento', label: 'Link de modelo', type: 'text', col: 'col-md-4' },
      { key: 'asignacionDocumento', label: 'Asignar documento a', type: 'select', required: true, options: DOCUMENT_ASSIGNMENT_OPTIONS, col: 'col-md-4' },
      {
        key: 'idCarreraAsignacion',
        label: 'Carrera destino',
        type: 'select',
        optionsEndpoint: 'carreras',
        optionValueKey: 'idCarrera',
        optionLabelKeys: ['nomCarrera', 'facultad.nomFacultad'],
        optionValueType: 'number',
        showWhenField: 'asignacionDocumento',
        showWhenValues: ['CARRERA', 'CARRERA_CICLO'],
        col: 'col-md-4',
      },
      {
        key: 'idCicloAsignacion',
        label: 'Ciclo destino',
        type: 'select',
        optionsEndpoint: 'ciclos',
        optionValueKey: 'idCiclo',
        optionLabelKeys: ['nomCiclo'],
        optionValueType: 'number',
        showWhenField: 'asignacionDocumento',
        showWhenValues: ['CICLO', 'CARRERA_CICLO'],
        col: 'col-md-4',
      },
      { key: 'descripcionDocumento', label: 'Descripcion', type: 'textarea', col: 'col-md-12' },
    ],
    columns: [
      { key: 'idDocumento', label: '#', type: 'number' },
      { key: 'nombreDocumento', label: 'Documento', type: 'text' },
      { key: 'estadoDocumento', label: 'Estado', type: 'text' },
      { key: 'asignacionDocumento', label: 'Asignacion', type: 'text' },
      { key: 'linkModeloDocumento', label: 'Link de modelo', type: 'text' },
    ],
    emptyRecord: {
      nombreDocumento: '',
      descripcionDocumento: '',
      linkModeloDocumento: '',
      estadoDocumento: 'ACTIVO',
      asignacionDocumento: 'TODOS',
      idCarreraAsignacion: '',
      idCicloAsignacion: '',
    },
  },
  estudiantes: {
    key: 'estudiantes',
    title: 'Estudiantes',
    subtitle: 'Registra estudiantes con carrera, ciclo y estado de vinculacion.',
    icon: 'pe-7s-users icon-gradient bg-strong-bliss',
    endpoint: 'estudiantes',
    idKey: 'idEstudiante',
    statusKey: 'estadoVinculacion.nomEstado',
    searchFields: ['cedulaEstudiante', 'nombreEstudiante', 'idCarrera', 'carrera.nomCarrera'],
    searchPlaceholder: 'Buscar por cedula, nombre o carrera',
    filters: [
      {
        key: 'carrera',
        label: 'Carrera',
        type: 'select',
        fields: ['idCarrera'],
        optionsEndpoint: 'carreras',
        optionValueKey: 'idCarrera',
        optionLabelKeys: ['nomCarrera'],
      },
      {
        key: 'vinculacion',
        label: 'Estado vinculacion',
        type: 'select',
        fields: ['idEstadoVinculacion'],
        optionsEndpoint: 'estados-vinculacion',
        optionValueKey: 'idEstado',
        optionLabelKeys: ['nomEstado'],
      },
    ],
    fields: [
      { key: 'cedulaEstudiante', label: 'Cedula', type: 'text', required: true, col: 'col-md-4' },
      { key: 'nombreEstudiante', label: 'Nombre completo', type: 'text', required: true, col: 'col-md-4' },
      { key: 'correoEstudiante', label: 'Correo', type: 'text', required: true, col: 'col-md-4' },
      {
        key: 'idCarrera',
        label: 'Carrera',
        type: 'select',
        required: true,
        optionsEndpoint: 'carreras',
        optionValueKey: 'idCarrera',
        optionLabelKeys: ['nomCarrera', 'facultad.nomFacultad'],
        optionValueType: 'number',
        col: 'col-md-4',
      },
      {
        key: 'idEstadoVinculacion',
        label: 'Estado de vinculacion',
        type: 'select',
        required: true,
        optionsEndpoint: 'estados-vinculacion',
        optionValueKey: 'idEstado',
        optionLabelKeys: ['nomEstado', 'desEstado'],
        optionValueType: 'number',
        col: 'col-md-4',
      },
      {
        key: 'idCiclo',
        label: 'Ciclo',
        type: 'select',
        required: true,
        optionsEndpoint: 'ciclos',
        optionValueKey: 'idCiclo',
        optionLabelKeys: ['nomCiclo'],
        optionValueType: 'number',
        col: 'col-md-4',
      },
      {
        key: 'idMalla',
        label: 'Malla',
        type: 'select',
        required: true,
        optionsEndpoint: 'mallas',
        optionValueKey: 'idMalla',
        optionLabelKeys: ['nomMalla', 'carrera.nomCarrera'],
        optionValueType: 'number',
        optionParentKey: 'idCarrera',
        dependsOnField: 'idCarrera',
        col: 'col-md-4',
      },
    ],
    columns: [
      { key: 'idEstudiante', label: '#', type: 'number' },
      { key: 'cedulaEstudiante', label: 'Cedula', type: 'text' },
      { key: 'nombreEstudiante', label: 'Nombre completo', type: 'text' },
      { key: 'carrera.nomCarrera', label: 'Carrera', type: 'text' },
      { key: 'estadoVinculacion.nomEstado', label: 'Vinculacion', type: 'text' },
      { key: 'ciclo.nomCiclo', label: 'Ciclo', type: 'text' },
      { key: 'malla.nomMalla', label: 'Malla', type: 'text' },
    ],
    emptyRecord: {
      cedulaEstudiante: '',
      nombreEstudiante: '',
      correoEstudiante: '',
      idCarrera: '',
      idEstadoVinculacion: '',
      idCiclo: '',
      idMalla: '',
    },
  },
  'matriculas-proyecto': {
    key: 'matriculas-proyecto',
    title: 'Matriculas proyecto',
    subtitle: 'Vincula estudiante, tutor, proyecto y periodo.',
    icon: 'pe-7s-note2 icon-gradient bg-love-kiss',
    endpoint: 'matriculas-proyecto',
    idKey: 'idMatricula',
    statusKey: 'estadoMatriculaProyecto',
    searchFields: [
      'idMatricula',
      'idTutor',
      'tutor.cedulaTutor',
      'tutor.nombreTutor',
      'idEstudiante',
      'estudiante.cedulaEstudiante',
      'estudiante.nombreEstudiante',
      'idProyecto',
      'proyecto.nombreProyecto',
      'idPeriodo',
      'periodo.fechInicio',
      'periodo.fechFin',
      'idCiclo',
      'ciclo.nomCiclo',
      'documentosAprobados',
      'totalDocumentos',
      'linkCarpeta',
      'observacionMatricula',
      'estadoVinculacionCalculado',
      'estadoMatriculaProyecto',
    ],
    searchPlaceholder: 'Buscar por cualquier valor de matricula',
    filters: [
      { key: 'tutor', label: 'Tutor', type: 'select', fields: ['idTutor'], optionsEndpoint: 'tutores', optionValueKey: 'idTutor', optionLabelKeys: ['nombreTutor'] },
      { key: 'estudiante', label: 'Estudiante', type: 'select', fields: ['idEstudiante'], optionsEndpoint: 'estudiantes', optionValueKey: 'idEstudiante', optionLabelKeys: ['nombreEstudiante'] },
      { key: 'proyecto', label: 'Proyecto', type: 'select', fields: ['idProyecto'], optionsEndpoint: 'proyectos', optionValueKey: 'idProyecto', optionLabelKeys: ['nombreProyecto'] },
      { key: 'periodo', label: 'Periodo', type: 'select', fields: ['idPeriodo'], optionsEndpoint: 'periodos', optionValueKey: 'idPeriodo', optionLabelKeys: ['fechInicio', 'fechFin'] },
      { key: 'ciclo', label: 'Ciclo', type: 'select', fields: ['idCiclo'], optionsEndpoint: 'ciclos', optionValueKey: 'idCiclo', optionLabelKeys: ['nomCiclo'] },
      { key: 'estadoVinculacion', label: 'Estado vinculacion', type: 'select', fields: ['estadoVinculacionCalculado'], options: ENROLLMENT_PROGRESS_STATE_OPTIONS },
      { key: 'estado', label: 'Estado matricula', type: 'select', fields: ['estadoMatriculaProyecto'], options: ENROLLMENT_STATE_OPTIONS },
    ],
    fields: [
      {
        key: 'idEstudiante',
        label: 'Estudiante',
        type: 'select',
        required: true,
        optionsEndpoint: 'estudiantes',
        optionValueKey: 'idEstudiante',
        optionLabelKeys: ['nombreEstudiante', 'cedulaEstudiante'],
        optionValueType: 'number',
        col: 'col-md-6',
      },
      {
        key: 'idProyecto',
        label: 'Proyecto',
        type: 'select',
        required: true,
        optionsEndpoint: 'proyectos',
        optionValueKey: 'idProyecto',
        optionLabelKeys: ['nombreProyecto', 'institucion.nomInstitucion'],
        optionValueType: 'number',
        col: 'col-md-6',
      },
      {
        key: 'idTutor',
        label: 'Tutor',
        type: 'select',
        required: true,
        optionsEndpoint: 'tutores',
        optionValueKey: 'idTutor',
        optionLabelKeys: ['nombreTutor', 'cedulaTutor'],
        optionValueType: 'number',
        col: 'col-md-6',
      },
      {
        key: 'idPeriodo',
        label: 'Periodo',
        type: 'select',
        required: true,
        optionsEndpoint: 'periodos',
        optionValueKey: 'idPeriodo',
        optionLabelKeys: ['fechInicio', 'fechFin'],
        optionValueType: 'number',
        col: 'col-md-6',
      },
      {
        key: 'idCiclo',
        label: 'Ciclo',
        type: 'select',
        required: true,
        optionsEndpoint: 'ciclos',
        optionValueKey: 'idCiclo',
        optionLabelKeys: ['nomCiclo'],
        optionValueType: 'number',
        col: 'col-md-4',
      },
      { key: 'linkCarpeta', label: 'Link carpeta', type: 'text', required: true, placeholder: 'Link de carpeta del estudiante', col: 'col-md-4' },
      { key: 'estadoMatriculaProyecto', label: 'Estado', type: 'select', required: true, options: ENROLLMENT_STATE_FORM_OPTIONS, col: 'col-md-4' },
      { key: 'observacionMatricula', label: 'Observacion', type: 'textarea', placeholder: 'Observaciones de la matricula', col: 'col-md-12' },
    ],
    columns: [
      { key: 'idMatricula', label: '#', type: 'number' },
      { key: 'estudiante.nombreEstudiante', label: 'Estudiante', type: 'text' },
      { key: 'proyecto.nombreProyecto', label: 'Proyecto', type: 'text' },
      { key: 'periodo.fechInicio', label: 'Periodo', type: 'date' },
      { key: 'ciclo.nomCiclo', label: 'Ciclo', type: 'text' },
      { key: 'documentosAprobados', label: 'Docs. aprobados', type: 'number' },
      { key: 'totalDocumentos', label: 'Total docs.', type: 'number' },
      { key: 'observacionMatricula', label: 'Observacion', type: 'text' },
      { key: 'progresoVinculacion', label: 'Progreso', type: 'text' },
      { key: 'estadoVinculacionCalculado', label: 'Estado vinculacion', type: 'text' },
      { key: 'estadoMatriculaProyecto', label: 'Estado matricula', type: 'text' },
    ],
    emptyRecord: {
      idTutor: '',
      idEstudiante: '',
      idProyecto: '',
      idPeriodo: '',
      idCiclo: '',
      linkCarpeta: '',
      observacionMatricula: '',
      estadoMatriculaProyecto: 'ACTIVO',
    },
  },
  'estudiante-documentos': {
    key: 'estudiante-documentos',
    title: 'Estudiante documentos',
    subtitle: 'Registra documentos entregados por matricula.',
    icon: 'pe-7s-copy-file icon-gradient bg-plum-plate',
    endpoint: 'estudiante-documentos',
    idKey: 'idEstudianteDocumento',
    statusKey: 'estadoEstudianteDocumento',
    searchFields: [
      'idEstudianteDocumento',
      'idDocumento',
      'documento.nombreDocumento',
      'idMatricula',
      'linkDocumento',
      'fechaAutorizacion',
      'estadoEstudianteDocumento',
    ],
    searchPlaceholder: 'Buscar por cualquier valor del documento',
    filters: [
      {
        key: 'estudiante',
        label: 'Estudiante',
        type: 'text',
        fields: [
          'matriculaProyecto.estudiante.cedulaEstudiante',
          'matriculaProyecto.estudiante.nombreEstudiante',
        ],
        placeholder: 'Cedula o nombre',
      },
      { key: 'estado', label: 'Estado', type: 'select', fields: ['estadoEstudianteDocumento'], options: DOCUMENT_STATE_OPTIONS },
    ],
    fields: [
      {
        key: 'idDocumento',
        label: 'Documento',
        type: 'select',
        required: true,
        optionsEndpoint: 'documentos',
        optionValueKey: 'idDocumento',
        optionLabelKeys: ['nombreDocumento'],
        optionValueType: 'number',
        col: 'col-md-4',
      },
      {
        key: 'idMatricula',
        label: 'Matricula',
        type: 'select',
        required: true,
        optionsEndpoint: 'matriculas-proyecto',
        optionValueKey: 'idMatricula',
        optionLabelKeys: [
          'estudiante.nombreEstudiante',
          'proyecto.nombreProyecto',
          'periodo.fechInicio',
          'periodo.fechFin',
          'ciclo.nomCiclo',
        ],
        optionValueType: 'number',
        col: 'col-md-4',
      },
      { key: 'fechaAutorizacion', label: 'Fecha autorizacion', type: 'date', required: true, col: 'col-md-4' },
      {
        key: 'estadoEstudianteDocumento',
        label: 'Estado',
        type: 'select',
        required: true,
        optionsEndpoint: 'estados',
        optionValueKey: 'nomEstado',
        optionLabelKeys: ['nomEstado'],
        optionValueType: 'string',
        col: 'col-md-4',
      },
      { key: 'linkDocumento', label: 'Link documento', type: 'text', hidden: true },
    ],
    columns: [
      { key: 'idEstudianteDocumento', label: '#', type: 'number' },
      { key: 'documento.nombreDocumento', label: 'Documento', type: 'text' },
      { key: 'matriculaProyecto.estudiante.nombreEstudiante', label: 'Estudiante', type: 'text' },
      { key: 'matriculaProyecto.proyecto.nombreProyecto', label: 'Proyecto', type: 'text' },
      { key: 'matriculaProyecto.periodo.fechInicio', label: 'Periodo', type: 'date' },
      { key: 'fechaAutorizacion', label: 'Fecha', type: 'date' },
      { key: 'estadoEstudianteDocumento', label: 'Estado', type: 'text' },
    ],
    emptyRecord: { idDocumento: '', idMatricula: '', linkDocumento: 'PENDIENTE', fechaAutorizacion: '', estadoEstudianteDocumento: 'PENDIENTE' },
  },
  'planificaciones-vinculacion': {
    key: 'planificaciones-vinculacion',
    title: 'Planificacion de vinculacion por carrera',
    subtitle: 'Planifica proyectos de vinculacion por periodo, carrera y proyecto.',
    icon: 'pe-7s-map-2 icon-gradient bg-happy-fisher',
    endpoint: 'planificaciones-vinculacion',
    idKey: 'idPlanificacion',
    searchFields: [
      'responsable.nomResponsable',
      'responsable.correoResponsable',
      'idResponsable',
      'observaciones',
      'link',
      'tutor.nombreTutor',
      'periodo.fechInicio',
      'periodo.fechFin',
      'carrera.nomCarrera',
      'proyecto.nombreProyecto',
    ],
    searchPlaceholder: 'Buscar por tutor, responsable, carrera, proyecto o periodo',
    filters: [
      { key: 'tutor', label: 'Tutor', type: 'select', fields: ['idTutor'], optionsEndpoint: 'tutores', optionValueKey: 'idTutor', optionLabelKeys: ['nombreTutor'] },
      { key: 'responsable', label: 'Responsable', type: 'select', fields: ['idResponsable'], optionsEndpoint: 'responsables', optionValueKey: 'idResponsable', optionLabelKeys: ['nomResponsable'] },
      { key: 'periodo', label: 'Periodo', type: 'select', fields: ['idPeriodo'], optionsEndpoint: 'periodos', optionValueKey: 'idPeriodo', optionLabelKeys: ['fechInicio', 'fechFin'] },
      { key: 'carrera', label: 'Carrera', type: 'select', fields: ['idCarrera'], optionsEndpoint: 'carreras', optionValueKey: 'idCarrera', optionLabelKeys: ['nomCarrera'] },
      { key: 'proyecto', label: 'Proyecto', type: 'select', fields: ['idProyecto'], optionsEndpoint: 'proyectos', optionValueKey: 'idProyecto', optionLabelKeys: ['nombreProyecto'] },
    ],
    fields: [
      {
        key: 'idTutor',
        label: 'Tutor',
        type: 'select',
        required: true,
        optionsEndpoint: 'tutores',
        optionValueKey: 'idTutor',
        optionLabelKeys: ['nombreTutor', 'cedulaTutor'],
        optionValueType: 'number',
        col: 'col-md-4',
      },
      {
        key: 'idResponsable',
        label: 'Responsable',
        type: 'select',
        required: true,
        optionsEndpoint: 'responsables',
        optionValueKey: 'idResponsable',
        optionLabelKeys: ['nomResponsable', 'correoResponsable'],
        optionValueType: 'number',
        col: 'col-md-4',
      },
      {
        key: 'idPeriodo',
        label: 'Periodo',
        type: 'select',
        required: true,
        optionsEndpoint: 'periodos',
        optionValueKey: 'idPeriodo',
        optionLabelKeys: ['fechInicio', 'fechFin'],
        optionValueType: 'number',
        col: 'col-md-4',
      },
      {
        key: 'idCarrera',
        label: 'Carrera',
        type: 'select',
        required: true,
        optionsEndpoint: 'carreras',
        optionValueKey: 'idCarrera',
        optionLabelKeys: ['nomCarrera', 'facultad.nomFacultad'],
        optionValueType: 'number',
        col: 'col-md-4',
      },
      {
        key: 'idProyecto',
        label: 'Proyecto',
        type: 'select',
        required: true,
        optionsEndpoint: 'proyectos',
        optionValueKey: 'idProyecto',
        optionLabelKeys: ['nombreProyecto', 'institucion.nomInstitucion'],
        optionValueType: 'number',
        col: 'col-md-4',
      },
      {
        key: 'numeroEstudiantes',
        label: 'Numero de estudiantes',
        type: 'number',
        required: true,
        col: 'col-md-4',
      },
      { key: 'link', label: 'Link', type: 'text', col: 'col-md-6' },
      { key: 'observaciones', label: 'Observaciones', type: 'textarea', col: 'col-md-6' },
    ],
    columns: [
      { key: 'idPlanificacion', label: '#', type: 'number' },
      { key: 'tutor.nombreTutor', label: 'Tutor', type: 'text' },
      { key: 'responsable.nomResponsable', label: 'Responsable', type: 'text' },
      { key: 'periodo.fechInicio', label: 'Periodo', type: 'date' },
      { key: 'carrera.nomCarrera', label: 'Carrera', type: 'text' },
      { key: 'proyecto.nombreProyecto', label: 'Proyecto', type: 'text' },
      { key: 'numeroEstudiantes', label: '# estudiantes', type: 'number' },
      { key: 'link', label: 'Link', type: 'text' },
    ],
    emptyRecord: {
      idTutor: '',
      idResponsable: '',
      link: '',
      observaciones: '',
      numeroEstudiantes: 0,
      idPeriodo: '',
      idCarrera: '',
      idProyecto: '',
    },
  },
  usuarios: {
    key: 'usuarios',
    title: 'Usuarios',
    subtitle: 'Administra usuarios del sistema.',
    icon: 'pe-7s-user icon-gradient bg-amy-crisp',
    endpoint: 'usuarios',
    idKey: 'id',
    searchFields: ['nombre', 'correo'],
    searchPlaceholder: 'Buscar por nombre o correo',
    fields: [
      { key: 'nombre', label: 'Nombre', type: 'text', required: true, col: 'col-md-6' },
      { key: 'username', label: 'Usuario', type: 'text', required: true, col: 'col-md-6' },
      { key: 'correo', label: 'Correo', type: 'text', required: true, col: 'col-md-6' },
      { key: 'direccion', label: 'Direccion', type: 'text', col: 'col-md-6' },
      { key: 'password', label: 'Password', type: 'password', required: true, col: 'col-md-6' },
    ],
    columns: [
      { key: 'id', label: '#', type: 'number' },
      { key: 'nombre', label: 'Nombre', type: 'text' },
      { key: 'username', label: 'Usuario', type: 'text' },
      { key: 'correo', label: 'Correo', type: 'text' },
    ],
    emptyRecord: { nombre: '', correo: '', direccion: '', username: '', password: '' },
  },
};

export const ADMIN_MENU_ITEMS = ADMIN_ENTITY_ORDER.map(key => ({
  key,
  title: ADMIN_ENTITIES[key].title,
  path: `/administracion/${key}`,
}));

export const ADMIN_MENU_GROUPS = [
  {
    id: 'gestionEstudiantesMenu',
    title: 'Gestion estudiantil',
    icon: 'pe-7s-users',
    items: ['estudiantes', 'matriculas-proyecto', 'estudiante-documentos'],
  },
  {
    id: 'vinculacionMenu',
    title: 'Vinculacion',
    icon: 'pe-7s-portfolio',
    items: ['proyectos', 'planificaciones-vinculacion'],
  },
  {
    id: 'configuracionBaseMenu',
    title: 'Configuracion base',
    icon: 'pe-7s-settings',
    items: [
      'estados',
      'estados-vinculacion',
      'facultades',
      'carreras',
      'mallas',
      'ciclos',
      'periodos',
      'tutores',
      'responsables',
      'instituciones',
      'documentos',
    ],
  },
  {
    id: 'sistemaMenu',
    title: 'Sistema',
    icon: 'pe-7s-config',
    items: ['usuarios'],
  },
].map(group => ({
  ...group,
  items: group.items.map(key => ({
    key,
    title: ADMIN_ENTITIES[key].title,
    path: `/administracion/${key}`,
  })),
}));
